### ISSUE TITLE
Epic: Licensing

### ISSUE THREAD

**Issue by egasimus** [hackbg/fadroma#154]
Fadroma is freely available under AGPL-3.0. A major unresolved issue in free software is encouraging non-contributing users to donate funds towards the long-term sustainability of the project. To that end, I suggest devising a privacy-preserving, offline-friendly donations/licensing mechanism.

* [ ] By default, Fadroma emits text that encourages users to donate; both to the terminal, when running various commands (maybe not every time but once every few runs), as well as to source files generated by the project scaffolding utility.
* [ ] To remove these, export a global environment variable `FADROMA_LICENSE=...`. When this is set, the encouragements in the terminal are replaced with thanks, and the ones in the source files are replaced by a single license confirmation.
* [ ] To generate a value for `FADROMA_LICENSE`, send funds to a licensing contract on Secret Network which contains the root license key.
* [ ] The Fadroma packages should contain a validating key which can confirm that the value of `FADROMA_LICENSE` was generated by the licensing contract without having to connect to the network.
* [ ] Donation info from the smart contract can be published at fadroma.tech to give a shout out to paying contributors
* [ ] The license keys can furthermore be matched to the identities of project contributors (SSH and/or GPG) to provide optional per-seat licensing.

**Comment by mradkov** [comment]
How do you propose we handle licensed usage outside of Secret Network?

The only problem with licensing this way I see is people will have to spend a lot of time acquiring SCRT via exchanges and setting wallets in order to issue a license (in case they want to) for the packages they use.

Possibly IBC 🤔.
