### ISSUE TITLE
Epic: Docker Compose integration and automatic code reloading

### ISSUE THREAD

**Issue by egasimus** [hackbg/fadroma#94]
* [ ] Scaffold Docker Compose-based project
* [ ] Container: build service
* [ ] Container: devnet service
* [ ] Container: devnet explorer
* [ ] Container: dev dashboard
* [ ] Container: blank frontend app (React/Vue/something Rust-based?)
* [ ] Container: blank backend app (Express + SQLite3?)
